In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import re
import numpy as np

# ****FOR FLIPKART WEBSITE****

**Data Extraction Process**

In [3]:
name =[]
prices = []
ratings = []
reviews = []
links = []
start_link = "https://www.flipkart.com"
df = pd.DataFrame()

In [4]:
page = 1
titles = []
while page != 50 :
      url = f"https://www.flipkart.com/search?q=laptops&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&as-pos=1&as-type=HISTORY&page={page}"
      response = requests.get(url)
      html = response.content   #retrieves the raw HTML content of the response, including any HTML tags, attributes, and text within the response.
      soup = BeautifulSoup(response.text,"html.parser")  # Initializes a BeautifulSoup object named soup using the HTML content as a string and specifies the parser to be used as "html.parser". 
                                                          #This allows you to parse and navigate the HTML structure of the webpage easily using BeautifulSoup methods and functions.
      data = soup.find_all("div",{"class":"_2kHMtA"})
      for h3 in soup.find_all("div",{"class":"_2kHMtA"}):

        titles.append(h3)
      page = page + 1

In [ ]:
len(titles)  #number of laptops that were extracted

984

In [ ]:
box = titles[0]  #to check for the format in the flipkart website
box

<div class="_2kHMtA"><div class="_2tfzpE"><span>Ad</span></div><a class="_1fQZEK" href="/lenovo-ideapad-gaming-3-ryzen-5-hexa-core-5600h-8-gb-1-tb-hdd-256-gb-ssd-windows-11-home-4-graphics-nvidia-geforce-gtx-1650-120-hz-gaming3-15ach6d1-laptop/p/itmabd3d828c1ad1?pid=COMGHMH6JRYP56GE&amp;lid=LSTCOMGHMH6JRYP56GE4TQDME&amp;marketplace=FLIPKART&amp;q=laptops&amp;store=6bo%2Fb5g&amp;srno=s_1_1&amp;otracker=search&amp;otracker1=search&amp;fm=organic&amp;iid=en_SutbCHmjBKxsI7OYz9v5TVaCytUcRzuCPFjGnYhgZuuRAau%2FyjB6S5wbSkeFN4mTNNTMRIJGxjMaJXLLVLJutA%3D%3D&amp;ppt=None&amp;ppn=None&amp;ssid=6i3nj74asw0000001684940907630&amp;qH=c06ea84a1e3dc3c6" rel="noopener noreferrer" target="_blank"><div class="MIXNux"><div class="_2QcLo-"><div><div class="CXW8mj" style="height:200px;width:200px"><img alt="Lenovo IdeaPad Gaming 3 Ryzen 5 Hexa Core 5600H - (8 GB/1 TB HDD/256 GB SSD/Windows 11 Home/4 GB Graph..." class="_396cs4" loading="eager" src="https://rukminim1.flixcart.com/image/312/312/xif0q/computer/v/k/d/14iau7-gaming-laptop-lenovo-original-imaghnq4zafgebtu.jpeg?q=70"/></div></div></div><div class="_3wLduG"><div class="_3PzNI-"><span class="f3A4_V"><label class="_2iDkf8"><input class="_30VH1S" readonly="" type="checkbox"/><div class="_24_Dny"></div></label></span><label class="_6Up2sF"><span>Add to Compare</span></label></div></div><div class="_2hVSre _3nq8ih"><div class="_36FSn5"><svg class="_1l0elc" height="16" viewbox="0 0 20 16" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eX72wL" d="M8.695 16.682C4.06 12.382 1 9.536 1 6.065 1 3.219 3.178 1 5.95 1c1.566 0 3.069.746 4.05 1.915C10.981 1.745 12.484 1 14.05 1 16.822 1 19 3.22 19 6.065c0 3.471-3.06 6.316-7.695 10.617L10 17.897l-1.305-1.215z" fill="#2874F0" fill-rule="evenodd" opacity=".9" stroke="#FFF"></path></svg></div></div></div><div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">Lenovo IdeaPad Gaming 3 Ryzen 5 Hexa Core 5600H - (8 GB/1 TB HDD/256 GB SSD/Windows 11 Home/4 GB Graph...</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTCOMGHMH6JRYP56GE4TQDME_COMGHMH6JRYP56GE_"><div class="_3LWZlK">4<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>25 Ratings </span><span class="_13vcmD">&amp;</span><span> 4 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">AMD Ryzen 5 Hexa Core Processor</li><li class="rgWa7D">8 GB DDR4 RAM</li><li class="rgWa7D">64 bit Windows 11 Operating System</li><li class="rgWa7D">1 TB HDD|256 GB SSD</li><li class="rgWa7D">39.62 cm (15.6 Inch) Display</li><li class="rgWa7D">1 Year Onsite Warranty + 1 Year Premium Care + 1 Year Accidental Damage Protection</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹52,990</div><div class="_3I9_wc _27UcVY">₹<!-- -->89,490</div><div class="_3Ay6Sb"><span>40% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹19,900</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:12px;font-weight:400">No Cost EMI from ₹8,661/month</div></div></div></div></div></a></div>

In [5]:
data_list = [] 
for box in titles:   #iterating through all the laptops

  temp_dict = {}
  temp_dict["Title"] = box.find('div',{'class':'_4rR01T'}).text.strip()   #getting specifications of the product

  temp_dict["Price(₹)"] = box.find('div',{'class':'_30jeq3 _1_WHN1'}).text.replace("₹","").strip() if box.find('div',{'class':'_30jeq3 _1_WHN1'}) else None   #price of the product
  temp_dict["Rating"] = box.find('div',{'class':"_3LWZlK"}).text.strip() if box.find("div", {"class": "_3LWZlK"}) else None     #rating of the product
  temp_dict["Reviews"] = reviews = box.find('span', attrs={'class' : '_2_R_DZ'}).text if box.find('span', attrs={'class' : '_2_R_DZ'}) else None   #reviews of the product
  rest_link = box.find('a')['href']
  #name_items =box.find('div',{'class': '_1fQZEK'})
  links = (start_link + rest_link)
  temp_dict["Product Links"] = links
  data_list.append(temp_dict)

In [ ]:
laptops_df = pd.DataFrame(data_list)
laptops_df

,Title,Price(₹),Rating,Reviews,Product Links
0,Lenovo IdeaPad Gaming 3 Ryzen 5 Hexa Core 5600...,"52,990",4,25 Ratings & 4 Reviews,https://www.flipkart.com/lenovo-ideapad-gaming...
1,Lenovo IdeaPad Ryzen 7 Octa Core 5800H - (16 G...,"69,990",4.4,72 Ratings & 8 Reviews,https://www.flipkart.com/lenovo-ideapad-ryzen-...
2,RedmiBook Pro Core i5 11th Gen - (8 GB/512 GB ...,"37,990",4.1,"5,507 Ratings & 622 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...
3,ASUS Vivobook 15 Core i3 11th Gen - (8 GB/512 ...,"34,990",4.2,"1,474 Ratings & 136 Reviews",https://www.flipkart.com/asus-vivobook-15-core...
4,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,"54,990",4.5,"5,294 Ratings & 573 Reviews",https://www.flipkart.com/asus-tuf-gaming-f15-c...
...,...,...,...,...,...
979,MSI Core i3 12th Gen - (8 GB/512 GB SSD/Window...,"42,990",4.5,11 Ratings & 3 Reviews,https://www.flipkart.com/msi-core-i3-12th-gen-...
980,DELL Core i3 11th Gen - (8 GB/1 TB HDD/Windows...,"42,500",4.3,7 Ratings & 0 Reviews,https://www.flipkart.com/dell-core-i3-11th-gen...
981,ASUS Core i3 11th Gen - (8 GB/512 GB SSD/Windo...,"36,750",None,None,https://www.flipkart.com/asus-core-i3-11th-gen...
982,ASUS Pentium Quad Core - (8 GB/256 GB SSD/Wind...,"31,900",None,None,https://www.flipkart.com/asus-pentium-quad-cor...
983,Vaio SE Series Core i5 8th Gen - (8 GB/512 GB ...,"58,990",3.9,83 Ratings & 15 Reviews,https://www.flipkart.com/vaio-se-series-core-i...

**Data Transformation:**

In [34]:
laptops_df = pd.DataFrame(data_list)
laptops_df

,Title,Price(₹),Rating,Reviews,Product Links
0,Primebook 4G Android Based MediaTek MT8788 - (...,"16,990",4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...
1,Primebook 4G Android Based MediaTek MT8788 - (...,"18,990",4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...
2,RedmiBook Pro Core i5 11th Gen - (8 GB/512 GB ...,"37,990",4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...
3,ASUS Vivobook 15 Core i3 11th Gen - (8 GB/512 ...,"34,990",4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...
4,Lenovo IdeaPad 3 Core i3 12th Gen - (8 GB/512 ...,"37,990",4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...
...,...,...,...,...,...
979,Lenovo IdeaPad Slim 3 Intel Core i3 12th Gen -...,"37,990",4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-slim-3...
980,Lenovo Ideapad 330s Core i5 8th Gen - (4 GB/1 ...,"52,490",4,21 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-330s-c...
981,ASUS ROG Zephyrus M16 (2022) with 90Whr Batter...,"1,74,990",None,None,https://www.flipkart.com/asus-rog-zephyrus-m16...
982,ASUS Pentium Quad Core - (8 GB/256 GB SSD/Wind...,"31,900",None,None,https://www.flipkart.com/asus-pentium-quad-cor...
983,Lenovo IdeaPad 3 Intel Core i3 11th Gen - (8 G...,"38,990",4.3,"5,242 Ratings & 484 Reviews",https://www.flipkart.com/lenovo-ideapad-3-inte...

In [35]:
laptops_df['Price(₹)'] = laptops_df['Price(₹)'].str.replace(',', '')

In [36]:
laptops_df['model'],laptops_df['Specifications'] = laptops_df["Title"].str.split('-',1).str
del laptops_df['Title']
laptops_df.head()

<ipython-input-36-ecca7ce829d3>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['model'],laptops_df['Specifications'] = laptops_df["Title"].str.split('-',1).str
<ipython-input-36-ecca7ce829d3>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['model'],laptops_df['Specifications'] = laptops_df["Title"].str.split('-',1).str

,Price(₹),Rating,Reviews,Product Links,model,Specifications
0,16990,4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,(4 GB/64 GB EMMC Storage/Prime OS) 4G Thin an...
1,18990,4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,(4 GB/128 GB EMMC Storage/Prime OS) 4G Thin a...
2,37990,4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...,RedmiBook Pro Core i5 11th Gen,(8 GB/512 GB SSD/Windows 11 Home) Thin and Li...
3,34990,4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...,ASUS Vivobook 15 Core i3 11th Gen,(8 GB/512 GB SSD/Windows 11 Home) X515EA-EJ32...
4,37990,4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...,Lenovo IdeaPad 3 Core i3 12th Gen,(8 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin...

In [37]:
laptops_df['RAM(GB)'],laptops_df['Hard Disk Drive'] = laptops_df["Specifications"].str.split('(',1).str
del laptops_df['Specifications']
laptops_df.head()

<ipython-input-37-ee3b3de57827>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['RAM(GB)'],laptops_df['Hard Disk Drive'] = laptops_df["Specifications"].str.split('(',1).str
<ipython-input-37-ee3b3de57827>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['RAM(GB)'],laptops_df['Hard Disk Drive'] = laptops_df["Specifications"].str.split('(',1).str

,Price(₹),Rating,Reviews,Product Links,model,RAM(GB),Hard Disk Drive
0,16990,4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,,4 GB/64 GB EMMC Storage/Prime OS) 4G Thin and ...
1,18990,4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,,4 GB/128 GB EMMC Storage/Prime OS) 4G Thin and...
2,37990,4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...,RedmiBook Pro Core i5 11th Gen,,8 GB/512 GB SSD/Windows 11 Home) Thin and Ligh...
3,34990,4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...,ASUS Vivobook 15 Core i3 11th Gen,,8 GB/512 GB SSD/Windows 11 Home) X515EA-EJ322W...
4,37990,4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...,Lenovo IdeaPad 3 Core i3 12th Gen,,8 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin a...

In [38]:
laptops_df['RAM(GB)'],laptops_df['Hard Disk'] = laptops_df["Hard Disk Drive"].str.split('/',1).str
del laptops_df['Hard Disk Drive']
laptops_df.head()

<ipython-input-38-937877900a55>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['RAM(GB)'],laptops_df['Hard Disk'] = laptops_df["Hard Disk Drive"].str.split('/',1).str
<ipython-input-38-937877900a55>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['RAM(GB)'],laptops_df['Hard Disk'] = laptops_df["Hard Disk Drive"].str.split('/',1).str

,Price(₹),Rating,Reviews,Product Links,model,RAM(GB),Hard Disk
0,16990,4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,4 GB,64 GB EMMC Storage/Prime OS) 4G Thin and Light...
1,18990,4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,4 GB,128 GB EMMC Storage/Prime OS) 4G Thin and Ligh...
2,37990,4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...,RedmiBook Pro Core i5 11th Gen,8 GB,512 GB SSD/Windows 11 Home) Thin and Light Laptop
3,34990,4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...,ASUS Vivobook 15 Core i3 11th Gen,8 GB,512 GB SSD/Windows 11 Home) X515EA-EJ322WS | X...
4,37990,4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...,Lenovo IdeaPad 3 Core i3 12th Gen,8 GB,512 GB SSD/Windows 11 Home) 15IAU7 Thin and Li...

In [39]:
laptops_df['RAM(GB)'] = laptops_df['RAM(GB)'].str.replace('GB', '')

In [40]:
laptops_df['HDD'],laptops_df['specifications'] = laptops_df["Hard Disk"].str.split('/',1).str
del laptops_df['Hard Disk']
laptops_df.head()

<ipython-input-40-d5977b3ecc1c>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['HDD'],laptops_df['specifications'] = laptops_df["Hard Disk"].str.split('/',1).str
<ipython-input-40-d5977b3ecc1c>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['HDD'],laptops_df['specifications'] = laptops_df["Hard Disk"].str.split('/',1).str

,Price(₹),Rating,Reviews,Product Links,model,RAM(GB),HDD,specifications
0,16990,4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,4,64 GB EMMC Storage,Prime OS) 4G Thin and Light Lapt...
1,18990,4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...,Primebook 4G Android Based MediaTek MT8788,4,128 GB EMMC Storage,Prime OS) 4G Thin and Light Lap...
2,37990,4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...,RedmiBook Pro Core i5 11th Gen,8,512 GB SSD,Windows 11 Home) Thin and Light Laptop
3,34990,4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...,ASUS Vivobook 15 Core i3 11th Gen,8,512 GB SSD,Windows 11 Home) X515EA-EJ322WS | X515EA-EJ328...
4,37990,4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...,Lenovo IdeaPad 3 Core i3 12th Gen,8,512 GB SSD,Windows 11 Home) 15IAU7 Thin and Light Laptop

In [41]:
laptops_df['Company'],laptops_df['Model'] = laptops_df["model"].str.split(' ',1).str
del laptops_df['model'] 
laptops_df.head()

<ipython-input-41-cef07114d64a>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['Company'],laptops_df['Model'] = laptops_df["model"].str.split(' ',1).str
<ipython-input-41-cef07114d64a>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['Company'],laptops_df['Model'] = laptops_df["model"].str.split(' ',1).str

,Price(₹),Rating,Reviews,Product Links,RAM(GB),HDD,specifications,Company,Model
0,16990,4.1,580 Ratings & 201 Reviews,https://www.flipkart.com/primebook-4g-android-...,4,64 GB EMMC Storage,Prime OS) 4G Thin and Light Lapt...,Primebook,4G Android Based MediaTek MT8788
1,18990,4.1,117 Ratings & 44 Reviews,https://www.flipkart.com/primebook-4g-android-...,4,128 GB EMMC Storage,Prime OS) 4G Thin and Light Lap...,Primebook,4G Android Based MediaTek MT8788
2,37990,4.1,"5,543 Ratings & 624 Reviews",https://www.flipkart.com/redmibook-pro-core-i5...,8,512 GB SSD,Windows 11 Home) Thin and Light Laptop,RedmiBook,Pro Core i5 11th Gen
3,34990,4.2,"1,944 Ratings & 180 Reviews",https://www.flipkart.com/asus-vivobook-15-core...,8,512 GB SSD,Windows 11 Home) X515EA-EJ322WS | X515EA-EJ328...,ASUS,Vivobook 15 Core i3 11th Gen
4,37990,4,64 Ratings & 5 Reviews,https://www.flipkart.com/lenovo-ideapad-3-core...,8,512 GB SSD,Windows 11 Home) 15IAU7 Thin and Light Laptop,Lenovo,IdeaPad 3 Core i3 12th Gen

In [42]:
laptops_df['Total Reviews'],laptops_df['Ratings'] = laptops_df["Reviews"].str.split(' ',1).str
del laptops_df['Reviews']  
del laptops_df['Ratings']
laptops_df.head()

<ipython-input-42-03ef260febaf>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  laptops_df['Total Reviews'],laptops_df['Ratings'] = laptops_df["Reviews"].str.split(' ',1).str
<ipython-input-42-03ef260febaf>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  laptops_df['Total Reviews'],laptops_df['Ratings'] = laptops_df["Reviews"].str.split(' ',1).str

,Price(₹),Rating,Product Links,RAM(GB),HDD,specifications,Company,Model,Total Reviews
0,16990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,64 GB EMMC Storage,Prime OS) 4G Thin and Light Lapt...,Primebook,4G Android Based MediaTek MT8788,580
1,18990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,128 GB EMMC Storage,Prime OS) 4G Thin and Light Lap...,Primebook,4G Android Based MediaTek MT8788,117
2,37990,4.1,https://www.flipkart.com/redmibook-pro-core-i5...,8,512 GB SSD,Windows 11 Home) Thin and Light Laptop,RedmiBook,Pro Core i5 11th Gen,"5,543"
3,34990,4.2,https://www.flipkart.com/asus-vivobook-15-core...,8,512 GB SSD,Windows 11 Home) X515EA-EJ322WS | X515EA-EJ328...,ASUS,Vivobook 15 Core i3 11th Gen,"1,944"
4,37990,4,https://www.flipkart.com/lenovo-ideapad-3-core...,8,512 GB SSD,Windows 11 Home) 15IAU7 Thin and Light Laptop,Lenovo,IdeaPad 3 Core i3 12th Gen,64

In [43]:
regex = r"(\d+\s?(?:GB|TB))\s?(\b(?:SSD|HDD)\b)"
laptops_df[['Hard Disk(GB)', 'Storage_Type']] = laptops_df['HDD'].str.extract(regex)
del laptops_df['HDD']  
del laptops_df['Storage_Type']
laptops_df.head()

,Price(₹),Rating,Product Links,RAM(GB),specifications,Company,Model,Total Reviews,Hard Disk(GB)
0,16990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Prime OS) 4G Thin and Light Lapt...,Primebook,4G Android Based MediaTek MT8788,580,NaN
1,18990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Prime OS) 4G Thin and Light Lap...,Primebook,4G Android Based MediaTek MT8788,117,NaN
2,37990,4.1,https://www.flipkart.com/redmibook-pro-core-i5...,8,Windows 11 Home) Thin and Light Laptop,RedmiBook,Pro Core i5 11th Gen,"5,543",512 GB
3,34990,4.2,https://www.flipkart.com/asus-vivobook-15-core...,8,Windows 11 Home) X515EA-EJ322WS | X515EA-EJ328...,ASUS,Vivobook 15 Core i3 11th Gen,"1,944",512 GB
4,37990,4,https://www.flipkart.com/lenovo-ideapad-3-core...,8,Windows 11 Home) 15IAU7 Thin and Light Laptop,Lenovo,IdeaPad 3 Core i3 12th Gen,64,512 GB

In [44]:
laptops_df['Hard Disk(GB)'] = laptops_df['Hard Disk(GB)'].str.replace('GB', '')
laptops_df['Hard Disk(GB)'] = laptops_df['Hard Disk(GB)'].str.replace('TB', '')

In [49]:
regex = r"((?:Windows \d+|Mac OS \w+))\b(.*)"
laptops_df[['Operating_System', 'Other_Details']] = laptops_df['specifications'].str.extract(regex)
del laptops_df['specifications']
del laptops_df['Other_Details']
laptops_df

,Price(₹),Rating,Product Links,RAM(GB),Company,Model,Total Reviews,Hard Disk(GB),Operating_System
0,16990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Primebook,4G Android Based MediaTek MT8788,580,NaN,NaN
1,18990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Primebook,4G Android Based MediaTek MT8788,117,NaN,NaN
2,37990,4.1,https://www.flipkart.com/redmibook-pro-core-i5...,8,RedmiBook,Pro Core i5 11th Gen,"5,543",512,Windows 11
3,34990,4.2,https://www.flipkart.com/asus-vivobook-15-core...,8,ASUS,Vivobook 15 Core i3 11th Gen,"1,944",512,Windows 11
4,37990,4,https://www.flipkart.com/lenovo-ideapad-3-core...,8,Lenovo,IdeaPad 3 Core i3 12th Gen,64,512,Windows 11
...,...,...,...,...,...,...,...,...,...
979,37990,4,https://www.flipkart.com/lenovo-ideapad-slim-3...,8,Lenovo,IdeaPad Slim 3 Intel Core i3 12th Gen,64,512,Windows 11
980,52490,4,https://www.flipkart.com/lenovo-ideapad-330s-c...,4,Lenovo,Ideapad 330s Core i5 8th Gen,21,1,Windows 10
981,174990,None,https://www.flipkart.com/asus-rog-zephyrus-m16...,16,ASUS,ROG Zephyrus M16 (2022) with 90Whr Battery Cor...,None,512,Windows 11
982,31900,None,https://www.flipkart.com/asus-pentium-quad-cor...,8,ASUS,Pentium Quad Core,None,256,Windows 11
983,38990,4.3,https://www.flipkart.com/lenovo-ideapad-3-inte...,8,Lenovo,IdeaPad 3 Intel Core i3 11th Gen,"5,242",512,Windows 11

In [50]:
laptops_df.head()

,Price(₹),Rating,Product Links,RAM(GB),Company,Model,Total Reviews,Hard Disk(GB),Operating_System
0,16990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Primebook,4G Android Based MediaTek MT8788,580,NaN,NaN
1,18990,4.1,https://www.flipkart.com/primebook-4g-android-...,4,Primebook,4G Android Based MediaTek MT8788,117,NaN,NaN
2,37990,4.1,https://www.flipkart.com/redmibook-pro-core-i5...,8,RedmiBook,Pro Core i5 11th Gen,"5,543",512,Windows 11
3,34990,4.2,https://www.flipkart.com/asus-vivobook-15-core...,8,ASUS,Vivobook 15 Core i3 11th Gen,"1,944",512,Windows 11
4,37990,4,https://www.flipkart.com/lenovo-ideapad-3-core...,8,Lenovo,IdeaPad 3 Core i3 12th Gen,64,512,Windows 11

In [52]:
laptops_df = laptops_df[['Company','Operating_System','Model','RAM(GB)', 'Hard Disk(GB)' ,'Price(₹)', 'Rating','Total Reviews','Product Links']]  #we have to del specifications if not needed
laptops_df

,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Price(₹),Rating,Total Reviews,Product Links
0,Primebook,NaN,4G Android Based MediaTek MT8788,4,NaN,16990,4.1,580,https://www.flipkart.com/primebook-4g-android-...
1,Primebook,NaN,4G Android Based MediaTek MT8788,4,NaN,18990,4.1,117,https://www.flipkart.com/primebook-4g-android-...
2,RedmiBook,Windows 11,Pro Core i5 11th Gen,8,512,37990,4.1,"5,543",https://www.flipkart.com/redmibook-pro-core-i5...
3,ASUS,Windows 11,Vivobook 15 Core i3 11th Gen,8,512,34990,4.2,"1,944",https://www.flipkart.com/asus-vivobook-15-core...
4,Lenovo,Windows 11,IdeaPad 3 Core i3 12th Gen,8,512,37990,4,64,https://www.flipkart.com/lenovo-ideapad-3-core...
...,...,...,...,...,...,...,...,...,...
979,Lenovo,Windows 11,IdeaPad Slim 3 Intel Core i3 12th Gen,8,512,37990,4,64,https://www.flipkart.com/lenovo-ideapad-slim-3...
980,Lenovo,Windows 10,Ideapad 330s Core i5 8th Gen,4,1,52490,4,21,https://www.flipkart.com/lenovo-ideapad-330s-c...
981,ASUS,Windows 11,ROG Zephyrus M16 (2022) with 90Whr Battery Cor...,16,512,174990,None,None,https://www.flipkart.com/asus-rog-zephyrus-m16...
982,ASUS,Windows 11,Pentium Quad Core,8,256,31900,None,None,https://www.flipkart.com/asus-pentium-quad-cor...
983,Lenovo,Windows 11,IdeaPad 3 Intel Core i3 11th Gen,8,512,38990,4.3,"5,242",https://www.flipkart.com/lenovo-ideapad-3-inte...

In [ ]:
laptops_df.to_csv("Laptops_df.csv",index = False,encoding = 'utf-8')

#****FOR AMAZON WEBSITE****

**Data Extraction**

In [ ]:
# Function to extract Product Title
def get_title(soup):
    try:
        title = soup.find("span", attrs={"id":'productTitle'})    # Outer Tag Object
        title_value = title.text                                  # Inner NavigatableString Object
        title_string = title_value.strip()                        # Title as a string value
    except AttributeError:
        title_string = ""

    return title_string

# Function to extract Product Price
def get_price(soup):
    try:
        price = soup.find("span", attrs={'class':'a-price aok-align-center reinventPricePriceToPayMargin priceToPay'}).find('span', attrs= {'class' : "a-price-whole"}).text
    except AttributeError:
            price = ""

    return price

# Function to extract Product Rating
def get_rating(soup):
    try:
        rating = soup.find("i", attrs={'class':'a-icon a-icon-star a-star-4-5'}).string.strip() 
    except AttributeError:
        try:
            rating = soup.find("span", attrs={'class':'a-icon-alt'}).string.strip()
        except:
            rating = ""	

    return rating

# Function to extract Number of User Reviews
def get_review_count(soup):
    try:
        review_count = soup.find("span", attrs={'id':'acrCustomerReviewText'}).string.strip()

    except AttributeError:
        review_count = ""	

    return review_count

In [ ]:

HEADERS = ({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0'})  #User-Agent header is used to mimic a web browser when making HTTP requests
page = 1
links_list = []       # Store the links
    
while page != 3:
    URL = f"https://www.amazon.in/s?k=laptops&page={page}&qid=1681297837&ref=sr_pg_{page}"
    product_links = []
    # HTTP Request
    webpage = requests.get(URL, headers=HEADERS)

    # Soup Object containing all data
    soup = BeautifulSoup(webpage.content, "html.parser")

    # Fetch links as List of Tag Objects
    links = soup.find_all("a", attrs={'class':'a-link-normal s-no-outline'})



    # Loop for extracting links from Tag Objects
    for link in links:
        links_list.append(link.get('href'))
    d = {"Title":[], "Price(₹)":[], "Rating":[], "Reviews":[]}
    
    # Loop for extracting product details from each link 
    for link in links_list:
        new_webpage = requests.get("https://www.amazon.in" + link, headers=HEADERS)
        product_links.append("https://www.amazon.in" + link)
        new_soup = BeautifulSoup(new_webpage.content, "html.parser")

        # Function calls to display all necessary product information
        d['Title'].append(get_title(new_soup))
        d['Price(₹)'].append(get_price(new_soup))
        d['Rating'].append(get_rating(new_soup)) 
        d['Reviews'].append(get_review_count(new_soup))
    d['Product Links'] = product_links
    page = page + 1
   
    amazon = pd.DataFrame.from_dict(d)
    
    amazon['Title'].replace('', np.nan, inplace=True)
    amazon = amazon.dropna(subset=['Title'])

In [ ]:
amazon_site = links[1]
amazon_site

<a class="a-link-normal s-no-outline" href="/Lenovo-IdeaPad-39-62cm-Warranty-82H802XXIN/dp/B0BN4JZVRR/ref=sr_1_18?keywords=laptops&amp;qid=1684935934&amp;sr=8-18" target="_blank"><div class="a-section aok-relative s-image-fixed-height"><img alt='Lenovo IdeaPad Slim 3 Intel Core i5 11th Gen 15.6" (39.62cm) FHD Laptop (16GB/512GB SSD/Win 11/Office 2021/2 Years Warrant...' class="s-image" data-image-index="18" data-image-latency="s-product-image" data-image-load="" data-image-source-density="1" src="https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY218_.jpg" srcset="https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY327_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY436_QL65_.jpg 2x, https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY545_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/51pEhVQaaDL._AC_UY654_QL65_.jpg 3x"/></div></a>

In [55]:
amazon.head(10)

,Specifications,Price(?),Rating,Reviews,Product Links
0,"Dell Inspiron 5518 Laptop, Intel Core i5-11320...","67,600",3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...
1,"MSI Modern 14, Intel 13th Gen. i3-1315U, 36CM ...","49,990",Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...
2,Lenovo E41-55 AMD 14-inch HD 220 Nits Antiglar...,"20,990",3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...
3,(Renewed) Lenovo T440p ThinkPad 4th Gen Intel ...,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...
4,"Dell New Inspiron 3515 Windows Laptop, AMD Ryz...","41,500",3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...
5,(Renewed) Lenovo IdeaPad Slim 3 Intel Core i3 ...,NaN,Previous page,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...
6,"ASUS VivoBook 15, Intel Celeron N4020, 15.6"" (...","26,780",3.0 out of 5 stars,37 ratings,https://www.amazon.in/ASUS-VivoBook-Integrated...
7,"Dell Inspiron 3525 Laptop, AMD Athlon Silver 3...","38,500",4.0 out of 5 stars,333 ratings,https://www.amazon.in/Dell-Inspiron-Graphics-A...
8,(Renewed) HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB...,NaN,2.7 out of 5 stars,3 ratings,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...
9,Lenovo V15 Intel Celeron N4020 15.6 inches HD ...,"22,999",3.5 out of 5 stars,3 ratings,https://www.amazon.in/Lenovo-Celeron-Windows-M...

**Data Transformation**

In [56]:
amazon = amazon.rename(columns={'Price(?)': 'Price(₹)'})
amazon = amazon.rename(columns={'Rating': 'Ratings'})
amazon.head(10)

,Specifications,Price(₹),Ratings,Reviews,Product Links
0,"Dell Inspiron 5518 Laptop, Intel Core i5-11320...","67,600",3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...
1,"MSI Modern 14, Intel 13th Gen. i3-1315U, 36CM ...","49,990",Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...
2,Lenovo E41-55 AMD 14-inch HD 220 Nits Antiglar...,"20,990",3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...
3,(Renewed) Lenovo T440p ThinkPad 4th Gen Intel ...,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...
4,"Dell New Inspiron 3515 Windows Laptop, AMD Ryz...","41,500",3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...
5,(Renewed) Lenovo IdeaPad Slim 3 Intel Core i3 ...,NaN,Previous page,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...
6,"ASUS VivoBook 15, Intel Celeron N4020, 15.6"" (...","26,780",3.0 out of 5 stars,37 ratings,https://www.amazon.in/ASUS-VivoBook-Integrated...
7,"Dell Inspiron 3525 Laptop, AMD Athlon Silver 3...","38,500",4.0 out of 5 stars,333 ratings,https://www.amazon.in/Dell-Inspiron-Graphics-A...
8,(Renewed) HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB...,NaN,2.7 out of 5 stars,3 ratings,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...
9,Lenovo V15 Intel Celeron N4020 15.6 inches HD ...,"22,999",3.5 out of 5 stars,3 ratings,https://www.amazon.in/Lenovo-Celeron-Windows-M...

In [57]:
amazon['Price(₹)'] = amazon['Price(₹)'].str.replace(',', '')

In [58]:
amazon.head()

,Specifications,Price(₹),Ratings,Reviews,Product Links
0,"Dell Inspiron 5518 Laptop, Intel Core i5-11320...",67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...
1,"MSI Modern 14, Intel 13th Gen. i3-1315U, 36CM ...",49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...
2,Lenovo E41-55 AMD 14-inch HD 220 Nits Antiglar...,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...
3,(Renewed) Lenovo T440p ThinkPad 4th Gen Intel ...,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...
4,"Dell New Inspiron 3515 Windows Laptop, AMD Ryz...",41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...

In [59]:
import pandas as pd

amazon['Company'] = amazon['Specifications'].str.extract(r"(?:\(Renewed\)\s)?([A-Za-z]+)")

amazon.head(10)

,Specifications,Price(₹),Ratings,Reviews,Product Links,Company
0,"Dell Inspiron 5518 Laptop, Intel Core i5-11320...",67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell
1,"MSI Modern 14, Intel 13th Gen. i3-1315U, 36CM ...",49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI
2,Lenovo E41-55 AMD 14-inch HD 220 Nits Antiglar...,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo
3,(Renewed) Lenovo T440p ThinkPad 4th Gen Intel ...,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo
4,"Dell New Inspiron 3515 Windows Laptop, AMD Ryz...",41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell
5,(Renewed) Lenovo IdeaPad Slim 3 Intel Core i3 ...,NaN,Previous page,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...,Lenovo
6,"ASUS VivoBook 15, Intel Celeron N4020, 15.6"" (...",26780,3.0 out of 5 stars,37 ratings,https://www.amazon.in/ASUS-VivoBook-Integrated...,ASUS
7,"Dell Inspiron 3525 Laptop, AMD Athlon Silver 3...",38500,4.0 out of 5 stars,333 ratings,https://www.amazon.in/Dell-Inspiron-Graphics-A...,Dell
8,(Renewed) HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB...,NaN,2.7 out of 5 stars,3 ratings,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...,HP
9,Lenovo V15 Intel Celeron N4020 15.6 inches HD ...,22999,3.5 out of 5 stars,3 ratings,https://www.amazon.in/Lenovo-Celeron-Windows-M...,Lenovo

In [60]:

regex = r"(?i)\b((?:Windows\s+\d+|Mac(?:Book)?|Linux|Unix|Ubuntu|DOS)\b)"
amazon['Operating_System'] = amazon['Specifications'].str.extract(regex, flags=re.IGNORECASE)
amazon['Operating_System'] = amazon['Operating_System'].str.replace('MacBook', 'Mac', regex=True)

In [62]:
amazon['company'],amazon['Model'] = amazon["Specifications"].str.split(' ',1).str
del amazon['company']
del amazon['Specifications'] 
amazon.head()

<ipython-input-62-8a969cfc8a3e>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  amazon['company'],amazon['Model'] = amazon["Specifications"].str.split(' ',1).str
<ipython-input-62-8a969cfc8a3e>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  amazon['company'],amazon['Model'] = amazon["Specifications"].str.split(' ',1).str

,Price(₹),Ratings,Reviews,Product Links,Company,Operating_System,Model
0,67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G..."
1,49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ..."
2,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...
3,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...
4,41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3..."

In [63]:
import pandas as pd
import re


pattern = r"(\d+)\s?[Gg][Bb]"

# Define a function to extract RAM information from a string
def extract_ram(description):
    match = re.search(pattern, description)
    if match:
        return match.group(0)
    else:
        return None

# Apply the function to the 'Product_Description' column and create a new column 'RAM'
amazon['Model'] = amazon['Model'].astype(str)
amazon['RAM(GB)'] = amazon['Model'].apply(extract_ram)

# Print dataframe
amazon

,Price(₹),Ratings,Reviews,Product Links,Company,Operating_System,Model,RAM(GB)
0,67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8GB
1,49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8GB
2,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4GB
3,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8 GB
4,41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8GB
...,...,...,...,...,...,...,...,...
287,53990,4.0 out of 5 stars,1 rating,https://www.amazon.in/ASUS-Vivobook-Laptop-Win...,ASUS,Windows 11,"Vivobook Go 15 (2023), AMD Ryzen 5 7520U, 15.6...",16GB
288,32000,3.9 out of 5 stars,43 ratings,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,HP,NaN,Chromebook X360 Intel Celeron N4020 14 inch(35...,4GB
289,29990,Previous page,NaN,https://www.amazon.in/Lenovo-3-3250U-7200RPM-W...,Lenovo,DOS,E41-55 Laptop Ryzen 3-3250U / 8GB RAM/ 1TB 720...,8GB
290,59999,3.9 out of 5 stars,199 ratings,https://www.amazon.in/Acer-12-Cores-Windows-Gr...,Acer,Windows 11,Aspire 5 Gaming Intel Core i5 12th gen (12-Cor...,8 GB
291,31990,3.7 out of 5 stars,175 ratings,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...,HP,NaN,15s-Ryzen 3 3250U 8GB SDRAM/256GB SSD 15.6inch...,8GB

In [64]:
amazon['RAM(GB)'] = amazon['RAM(GB)'].str.replace('GB', '')

In [65]:
amazon['hard disk'] = amazon['Model'].str.extract(r"(\d+\s?(?:[Gg][Bb]|[Tt][Bb])?\s?(?:HDD|SSD|SDD))")

amazon

,Price(₹),Ratings,Reviews,Product Links,Company,Operating_System,Model,RAM(GB),hard disk
0,67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512GB SSD
1,49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN
2,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256GB SSD
3,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500 GB HDD
4,41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1TB HDD
...,...,...,...,...,...,...,...,...,...
287,53990,4.0 out of 5 stars,1 rating,https://www.amazon.in/ASUS-Vivobook-Laptop-Win...,ASUS,Windows 11,"Vivobook Go 15 (2023), AMD Ryzen 5 7520U, 15.6...",16,512GB SSD
288,32000,3.9 out of 5 stars,43 ratings,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,HP,NaN,Chromebook X360 Intel Celeron N4020 14 inch(35...,4,NaN
289,29990,Previous page,NaN,https://www.amazon.in/Lenovo-3-3250U-7200RPM-W...,Lenovo,DOS,E41-55 Laptop Ryzen 3-3250U / 8GB RAM/ 1TB 720...,8,NaN
290,59999,3.9 out of 5 stars,199 ratings,https://www.amazon.in/Acer-12-Cores-Windows-Gr...,Acer,Windows 11,Aspire 5 Gaming Intel Core i5 12th gen (12-Cor...,8,512 GB SSD
291,31990,3.7 out of 5 stars,175 ratings,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...,HP,NaN,15s-Ryzen 3 3250U 8GB SDRAM/256GB SSD 15.6inch...,8,256GB SSD

In [66]:
amazon['Hard Disk(GB)'],amazon['ssd'] = amazon["hard disk"].str.split(' ',1).str
del amazon['ssd'] 
del amazon['hard disk']
amazon.head()

<ipython-input-66-f7e34c3b2982>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  amazon['Hard Disk(GB)'],amazon['ssd'] = amazon["hard disk"].str.split(' ',1).str
<ipython-input-66-f7e34c3b2982>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  amazon['Hard Disk(GB)'],amazon['ssd'] = amazon["hard disk"].str.split(' ',1).str

,Price(₹),Ratings,Reviews,Product Links,Company,Operating_System,Model,RAM(GB),Hard Disk(GB)
0,67600,3.9 out of 5 stars,27 ratings,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512GB
1,49990,Previous page,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN
2,20990,3.4 out of 5 stars,5 ratings,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256GB
3,NaN,3.6 out of 5 stars,86 ratings,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500
4,41500,3.4 out of 5 stars,6 ratings,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1TB

In [68]:
amazon['Hard Disk(GB)'] = amazon['Hard Disk(GB)'].str.replace('GB', '')
amazon['Hard Disk(GB)'] = amazon['Hard Disk(GB)'].str.replace('TB', '')

In [69]:
amazon['Total Reviews'],amazon['ratings'] = amazon["Reviews"].str.split(' ',1).str
del amazon['Reviews'] 
del amazon['ratings'] 
amazon.head()

<ipython-input-69-bad9e0bf87fa>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  amazon['Total Reviews'],amazon['ratings'] = amazon["Reviews"].str.split(' ',1).str
<ipython-input-69-bad9e0bf87fa>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  amazon['Total Reviews'],amazon['ratings'] = amazon["Reviews"].str.split(' ',1).str

,Price(₹),Ratings,Product Links,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Total Reviews
0,67600,3.9 out of 5 stars,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512,27
1,49990,Previous page,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN,NaN
2,20990,3.4 out of 5 stars,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256,5
3,NaN,3.6 out of 5 stars,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500,86
4,41500,3.4 out of 5 stars,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1,6

In [70]:
amazon['Rating'],amazon['Out of'] = amazon["Ratings"].str.split(' ',1).str
del amazon['Ratings']
del amazon['Out of']  
amazon.head(10)

<ipython-input-70-63d71ee33523>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  amazon['Rating'],amazon['Out of'] = amazon["Ratings"].str.split(' ',1).str
<ipython-input-70-63d71ee33523>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  amazon['Rating'],amazon['Out of'] = amazon["Ratings"].str.split(' ',1).str

,Price(₹),Product Links,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Total Reviews,Rating
0,67600,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512,27,3.9
1,49990,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN,NaN,Previous
2,20990,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256,5,3.4
3,NaN,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500,86,3.6
4,41500,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1,6,3.4
5,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...,Lenovo,Windows 11,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 1...,8,512,NaN,Previous
6,26780,https://www.amazon.in/ASUS-VivoBook-Integrated...,ASUS,Windows 11,"VivoBook 15, Intel Celeron N4020, 15.6"" (39.62...",4,1,37,3.0
7,38500,https://www.amazon.in/Dell-Inspiron-Graphics-A...,Dell,NaN,"Inspiron 3525 Laptop, AMD Athlon Silver 3050U,...",8,256,333,4.0
8,NaN,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...,HP,NaN,HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB SSD 15.6i...,8,256,3,2.7
9,22999,https://www.amazon.in/Lenovo-Celeron-Windows-M...,Lenovo,Windows 11,V15 Intel Celeron N4020 15.6 inches HD Laptop ...,4,256,3,3.5

In [71]:
amazon.head(15)

,Price(₹),Product Links,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Total Reviews,Rating
0,67600,https://www.amazon.in/Dell-Inspiron-i5-11320H-...,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512,27,3.9
1,49990,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN,NaN,Previous
2,20990,https://www.amazon.in/Lenovo-Antiglare-Integra...,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256,5,3.4
3,NaN,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500,86,3.6
4,41500,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1,6,3.4
5,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...,Lenovo,Windows 11,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 1...,8,512,NaN,Previous
6,26780,https://www.amazon.in/ASUS-VivoBook-Integrated...,ASUS,Windows 11,"VivoBook 15, Intel Celeron N4020, 15.6"" (39.62...",4,1,37,3.0
7,38500,https://www.amazon.in/Dell-Inspiron-Graphics-A...,Dell,NaN,"Inspiron 3525 Laptop, AMD Athlon Silver 3050U,...",8,256,333,4.0
8,NaN,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...,HP,NaN,HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB SSD 15.6i...,8,256,3,2.7
9,22999,https://www.amazon.in/Lenovo-Celeron-Windows-M...,Lenovo,Windows 11,V15 Intel Celeron N4020 15.6 inches HD Laptop ...,4,256,3,3.5
10,129990,https://www.amazon.in/ASUS-Zenbook-Screen-Lapt...,ASUS,NaN,Zenbook Pro 14 Duo OLED (2022) Dual Screen Lap...,16,1,3,4.5
11,84990,https://www.amazon.in/HP-7-5800H-Graphics-Resp...,HP,NaN,Victus AMD Ryzen 7-5800H 15.6 inch(39.6 cm) FH...,16,512,1,5.0
12,99990,https://www.amazon.in/MSI-i7-12650H-Windows-Ge...,MSI,Windows 11,"Thin GF63, Intel 12th Gen. i7-12650H, 40CM FHD...",8,NaN,NaN,Previous
13,NaN,https://www.amazon.in/Renewed-Lenovo-ThinkPad-...,Lenovo,Windows 11,Lenovo ThinkPad 6th Gen Intel Core i5 Thin & L...,8,256,1,4.0
14,NaN,https://www.amazon.in/Refurbished-HP-Chromeboo...,HP,NaN,HP Chromebook 11A G6 EE 11.6 inches HD Chromeb...,4,NaN,40,3.1

In [73]:
amazon = amazon[['Company','Operating_System','Model','RAM(GB)', 'Hard Disk(GB)' ,'Price(₹)', 'Rating','Total Reviews','Product Links']]  #we have to del specifications if not needed
amazon.head(10)

,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Price(₹),Rating,Total Reviews,Product Links
0,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512,67600,3.9,27,https://www.amazon.in/Dell-Inspiron-i5-11320H-...
1,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN,49990,Previous,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...
2,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256,20990,3.4,5,https://www.amazon.in/Lenovo-Antiglare-Integra...
3,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500,NaN,3.6,86,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...
4,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1,41500,3.4,6,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...
5,Lenovo,Windows 11,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 1...,8,512,NaN,Previous,NaN,https://www.amazon.in/Renewed-Lenovo-IdeaPad-3...
6,ASUS,Windows 11,"VivoBook 15, Intel Celeron N4020, 15.6"" (39.62...",4,1,26780,3.0,37,https://www.amazon.in/ASUS-VivoBook-Integrated...
7,Dell,NaN,"Inspiron 3525 Laptop, AMD Athlon Silver 3050U,...",8,256,38500,4.0,333,https://www.amazon.in/Dell-Inspiron-Graphics-A...
8,HP,NaN,HP 15s-Ryzen 3 3250U 8GB SDRAM/256GB SSD 15.6i...,8,256,NaN,2.7,3,https://www.amazon.in/HP-15s-Ryzen-15-6inch-Mi...
9,Lenovo,Windows 11,V15 Intel Celeron N4020 15.6 inches HD Laptop ...,4,256,22999,3.5,3,https://www.amazon.in/Lenovo-Celeron-Windows-M...

In [74]:
combined_df = pd.concat([amazon,laptops_df], ignore_index=True)

In [75]:
combined_df

,Company,Operating_System,Model,RAM(GB),Hard Disk(GB),Price(₹),Rating,Total Reviews,Product Links
0,Dell,NaN,"Inspiron 5518 Laptop, Intel Core i5-11320H, 8G...",8,512,67600,3.9,27,https://www.amazon.in/Dell-Inspiron-i5-11320H-...
1,MSI,Windows 11,"Modern 14, Intel 13th Gen. i3-1315U, 36CM FHD ...",8,NaN,49990,Previous,NaN,https://www.amazon.in/MSI-Modern-14-i3-1315U-C...
2,Lenovo,Windows 10,E41-55 AMD 14-inch HD 220 Nits Antiglare Thin ...,4,256,20990,3.4,5,https://www.amazon.in/Lenovo-Antiglare-Integra...
3,Lenovo,Windows 10,Lenovo T440p ThinkPad 4th Gen Intel Core i5 - ...,8,500,NaN,3.6,86,https://www.amazon.in/Renewed-Lenovo-T440p-Thi...
4,Dell,NaN,"New Inspiron 3515 Windows Laptop, AMD Ryzen3-3...",8,1,41500,3.4,6,https://www.amazon.in/Dell-Inspiron-Ryzen3-325...
...,...,...,...,...,...,...,...,...,...
1271,Lenovo,Windows 11,IdeaPad Slim 3 Intel Core i3 12th Gen,8,512,37990,4,64,https://www.flipkart.com/lenovo-ideapad-slim-3...
1272,Lenovo,Windows 10,Ideapad 330s Core i5 8th Gen,4,1,52490,4,21,https://www.flipkart.com/lenovo-ideapad-330s-c...
1273,ASUS,Windows 11,ROG Zephyrus M16 (2022) with 90Whr Battery Cor...,16,512,174990,None,None,https://www.flipkart.com/asus-rog-zephyrus-m16...
1274,ASUS,Windows 11,Pentium Quad Core,8,256,31900,None,None,https://www.flipkart.com/asus-pentium-quad-cor...
1275,Lenovo,Windows 11,IdeaPad 3 Intel Core i3 11th Gen,8,512,38990,4.3,"5,242",https://www.flipkart.com/lenovo-ideapad-3-inte...

In [76]:
combined_df.to_csv("flip_amaz_dataset.csv",index = True,encoding = 'utf-8')